//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundSystem_University.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizedSignatory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuthorizedSignatory()
        {
            this.ApplicationApprovalStatus = new HashSet<ApplicationApprovalStatu>();
            this.DepartmentManagers = new HashSet<DepartmentManager>();
            this.Entities = new HashSet<Entity>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string JobType { get; set; }
        public int UserId { get; set; }
        public string CellPhone { get; set; }
        public Nullable<byte> OrderForCancellationTypeNotOnRegistrationDay { get; set; }
        public Nullable<byte> OrderForCancellationTypeOnRegistrationDay { get; set; }
        public string SignaturePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationApprovalStatu> ApplicationApprovalStatus { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepartmentManager> DepartmentManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity> Entities { get; set; }
    }
}
