//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundSystem_University.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationApprovalStatu> ApplicationApprovalStatus { get; set; }
        public virtual DbSet<AuthorizedSignatory> AuthorizedSignatories { get; set; }
        public virtual DbSet<CancellationType> CancellationTypes { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepartmentManager> DepartmentManagers { get; set; }
        public virtual DbSet<Entity> EntitiesTable { get; set; }
        public virtual DbSet<Form> Forms { get; set; }
        public virtual DbSet<ProcessManager> ProcessManagers { get; set; }
        public virtual DbSet<RefundApplicationFile> RefundApplicationFiles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<RefundApplication> RefundApplications { get; set; }
        public virtual DbSet<ApprovedRefundApplicationEmailCcRecipient> ApprovedRefundApplicationEmailCcRecipients { get; set; }
    }
}
