//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefundSystem_University.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RefundApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RefundApplication()
        {
            this.ApplicationApprovalStatus = new HashSet<ApplicationApprovalStatu>();
            this.RefundApplicationFiles = new HashSet<RefundApplicationFile>();
        }
    
        public int Id { get; set; }
        public int EntityId { get; set; }
        public int FormId { get; set; }
        public int UserId { get; set; }
        public int DepartmentId { get; set; }
        public int ProcessManagerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerIdNumber { get; set; }
        public string CreditLastDigits { get; set; }
        public Nullable<byte> RefundMethod { get; set; }
        public string AccountOwnerName { get; set; }
        public string BankNumber { get; set; }
        public string BranchNumber { get; set; }
        public string AccountNumber { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal TransactionAmount { get; set; }
        public string CancellationReason { get; set; }
        public bool FullCancellation { get; set; }
        public decimal RefundAmount { get; set; }
        public bool AdditionalCredit { get; set; }
        public string Details { get; set; }
        public string Remarks { get; set; }
        public System.DateTime Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationApprovalStatu> ApplicationApprovalStatus { get; set; }
        public virtual Department Department { get; set; }
        public virtual Entity Entity { get; set; }
        public virtual Form Form { get; set; }
        public virtual ProcessManager ProcessManager { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RefundApplicationFile> RefundApplicationFiles { get; set; }
    }
}
